sudo: required
dist: trusty
language: node_js
node_js:
  - '6.12.3'

cache:
  directories:
     - ./node_modules

params:
- env

addons:
  browserstack:
    username: 
    #  secure: "loqJJ161XY2BSkZZy+ccNA2KPToOTEPMJuvbk9Dqf+OZmXSUyKMtHnn3PjOWn+c9SZZEoLWtnYr6aBgBpD9zADhNFjzHmCNy4HYMJ1AcZ8dZFJci6tI+cdyO1F+62PCLu7vtwJOpnABRakbAhB8zVTrk0WgYK6kbmb7lyFaawZXF/AgOAQmo/OUKWVIDtkMp0ZGqbCffWRZIwm0L6mj6DBGXJyp7Ab94lX+oCAXF+3AUK+gD3jhRMu1zS+rtuoj4wCdZxLNlEduDKF2BNr2y6QgFetle50Y9idDAmaI0EWm31/iNKdcVpWWEaO4l94o9zftv59gIuNEirn9j/xd9mNiMd+bxjjHePrhzUBLpgkRfdCK3loIQaCSIspa6CcaOzLbU8Ju0FO3mmvgmrgE73EkbMjXYnMKRZ7uREBY95vd3oDIvYdPK+GIjWDuKyyFb0gE38Ejzmdi4sZPjHlJCA8928OmqRmMgkddgYpIqqf6gRfKwLygtBxSRAKUa+5mhy8sCP+/DPGNeLg1olDqcL11g1oAs1RVZVrxoAHkdouliQm3dQUKOev2axXgkWfXfd+Yxuf2nNGFg+GxMYPx6Sa5ZcTalk971Le8yY34TVwwp1+9fQOouXufN4H8uq1oVZRxQKBxus0nxPQq4jGqSja7J8bNkPblISwBWabjarJo="
    secure: "$BROWSERSTACK_USER"

    access_key: 
    #  secure: "vfD6o1AHnOw769asKAferS801NRLbFwQt8DHmeqHLkOehzlnlWFW1DFRHk4NBBQMZ4mrzTQxoWn5zqONlBqJXgPg/RCwDA8oL+6r+pu72LiWgtWXIbANUhQcCgm4t//Rj2Sr9dg1Lf7q8M0G+dH3Fa9Mz4iH+VqQ1JhEtb0/2d34/6pENPmHTqRXL1ryxvZCKtOkx3mEB6WWdrcEPFZLkTz2QU4f5sHsNsand8kzH8gdzqbpLximNDPy2QB43ayCf2mNGsNO87tcJUOiEu8z+4Y67P8POb6pSpFf3o/dZ6LCsFbeHIbZbSHtoyiA9BmWZLWcZtuQUAdYYRtp30eq6z7FZyFP2l1X6vF9sEKmuIbcQ+RDzRyKRmJkipxZ42pxWfjdRc5Xm2NkxqRA7/qnDD1N0yqjrkNm5xo+lnxJjPFoc6WrqWt6i5a/b68fvapgNj+wXECUzkKBLotbnzO3WSxE0olg3YSa+zPNNAIX/OBfti0ZdUNtmigMFkypXO0yaN0o5trrFkyi0QCpDqyR9DfRGkZCT6gkaS4rqSO4dez1AGCtFqEXQZSkzPQvXw+EATsb4+zQDJ2Qp01cbCaMkD7YlHnxpjipcElEFfheUTmf/ZV0Oj9VQwHepQrycQfBuhe/8t62wcBcZgKOeGFeZa+KCLLieBUVIseNVGjGChA="
    secure: "$BROWSERSTACK_ACCESS_KEY"
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: karma start karma.conf.js --single-run